routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'Admin\HomeController@index')->name('home');

Route::group(
    [
        "as"            =>  "admin.company.",
        "prefix"        =>  "company",
        "namespace"     =>  "Admin",
    ],
    function() {
        Route::get('/',
            [
                "uses"  => "CompanyController@index",
                "as"    => "home",
            ]
        );
        Route::get('/create',
            [
                "uses"  =>  "CompanyController@create",
                "as"    =>  "create"
            ]
        );
        Route::post('/create',
            [
                "uses"  => "CompanyController@store",
            ]
        );
        Route::get('/edit/{id}',
            [
                "uses"  => "CompanyController@edit",
                "as"    => "edit"
            ]
        );
        Route::post('/edit/{id}',
            [
                "uses"  => "CompanyController@update",
            ]
        );
        Route::get('/delete/{id}',
            [
                "uses"  => "CompanyController@destroy",
                "as"    => "delete"
            ]
        );
    }
);

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Admin;
class Company extends Model
{
    protected $fillable = [
        'name',
        'email',
        'logo',
        'website',
        'added_by',
    ];
    
    public function addedByAdmin()
    {
        return $this->hasOne(Admin::class, 'id', 'added_by');
    }
}

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Admin\AdminController;
use App\Models\Company;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;

class CompanyController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Companies = Company::with(['addedByAdmin'])->paginate(config('vars.Pagination'));
        return view('company.home')->with(['Companies' => $Companies]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['email', 'max:255', 'unique:companies,email'],
            'website' => ['max:255'],
            'logo' =>   ['dimensions:min_width=100,min_height=100']
        ]);
        $logoFileName = null;
        if($request->hasFile('logo')) {
            $logo = $request->file('logo');
            $logoFileName = time() . '.' . $logo->getClientOriginalExtension();
            Storage::disk('public')->put('Company/'.$logoFileName,  File::get($logo));
        }
        Company::create([
            'name'          =>   $request->post('name'),
            'email'         =>   $request->post('email'),
            'website'       =>   $request->post('website'),
            'logo'          =>   $logoFileName,
            'added_by'      =>   $this->AuthAdmin->user()->id ?? null,
        ]);
        return redirect()->back()->withSuccess("Company created successfully!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Company = Company::find($id);
        return view('company.edit')->with(['Company' => $Company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['email', 'max:255', 'unique:companies,email,'.$id],
            'website' => ['max:255'],
            'logo' =>   ['dimensions:min_width=100,min_height=100']
        ]);

        $Company            = Company::find($id);
        $logoFileName       = $Company->logo;
        if($request->hasFile('logo')) {
            $logo = $request->file('logo');
            $logoFileName = time() . '.' . $logo->getClientOriginalExtension();
            Storage::disk('public')->put('Company/'.$logoFileName,  File::get($logo));
        }
        
        $Company->name      =  $request->post('name');
        $Company->email     =  $request->post('email');
        $Company->website   =  $request->post('website');
        $Company->logo      =  $logoFileName;
        $Company->save();

        return redirect()->back()->withSuccess("Company updated successfully!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Company = Company::destroy($id);
        return redirect()->back()->withSuccess("Company deleted successfully!");
    }
}

resources/views/company/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 mb-3">
            <a href="{{ route('admin.company.home') }}" class="btn btn-primary float-right">All Company</a>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Add Comapny') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <form method="POST" action="{{ route('admin.company.create') }}" enctype="multipart/form-data">
                        @csrf
                        @if(session()->get('success'))
                        <div class="form-group row mb-1">
                            <div class="col-md-6 offset-md-4">
                                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                                        {{ session()->get('success') }}  
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                            </div>
                        </div>
                        @endif
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>
                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        
                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>
                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" autocomplete="email">
                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="website" class="col-md-4 col-form-label text-md-right">{{ __('Website') }}</label>
                            <div class="col-md-6">
                                <input id="website" type="text" class="form-control @error('website') is-invalid @enderror" name="website" value="{{ old('website') }}" autocomplete="website" autofocus>
                                @error('website')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="logo" class="col-md-4 col-form-label text-md-right">{{ __('Logo') }}</label>
                            <div class="col-md-6">
                                <div class="custom-file @error('logo') is-invalid @enderror">
                                    <input type="file" class="custom-file-input" id="logo" name="logo">
                                    <label class="custom-file-label" for="logo">Choose file</label>
                                </div>
                                @error('logo')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-1">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-success">
                                    {{ __('Add') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
    <script>
        $('#logo').on('change',function(){
            var fileName = $(this).val();
            $(this).next('.custom-file-label').html(fileName);
        })
    </script>
@endpush

resources/views/company/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 mb-3">
            <a href="{{ route('admin.company.home') }}" class="btn btn-primary float-right">All Company</a>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Edit Comapny') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <form method="POST" action="{{ route('admin.company.edit', ['id' => $Company->id]) }}" enctype="multipart/form-data">
                        @csrf
                        @if(session()->get('success'))
                        <div class="form-group row mb-1">
                            <div class="col-md-6 offset-md-4">
                                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                                        {{ session()->get('success') }}  
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                            </div>
                        </div>
                        @endif
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>
                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') ?? $Company->name }}" required autocomplete="name" autofocus>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        
                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>
                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') ?? $Company->email }}" required autocomplete="email">
                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="website" class="col-md-4 col-form-label text-md-right">{{ __('Website') }}</label>
                            <div class="col-md-6">
                                <input id="website" type="text" class="form-control @error('website') is-invalid @enderror" name="website" value="{{ old('website') ?? $Company->website }}" required autocomplete="website" autofocus>
                                @error('website')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="logo" class="col-md-4 col-form-label text-md-right">{{ __('Logo') }}</label>
                            <div class="col-md-6">
                                <img class="img-thumbnail" style="max-width: 10rem" src="{{ url('storage/Company/'.$Company->logo)}}" alt="{{$Company->logo}}">
                                <div class="custom-file @error('logo') is-invalid @enderror">
                                    <input type="file" class="custom-file-input" id="logo" name="logo">
                                    <label class="custom-file-label" for="logo">Change Logo</label>
                                </div>
                                @error('logo')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-1">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-success">
                                    {{ __('Update') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
    <script>
        $('#logo').on('change',function(){
            var fileName = $(this).val();
            $(this).next('.custom-file-label').html(fileName);
        })
    </script>
@endpush

resources/views/company/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 mb-3">
            <a href="{{ route('admin.company.create') }}" class="btn btn-primary float-right">Add Company</a>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Companies') }}</div>
                <div class="card-body">
                    <div class="float-right">{{ $Companies->links() }}</div>
                    <table class="table table-bordered table-hover table-condensed">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Website</th>
                                <th>Logo</th>
                                <th>Added By</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if(count($Companies) > 0)
                                @foreach($Companies as $Company)
                                    <tr>
                                        <td>{{$Company->name}}</td>
                                        <td>{{$Company->email}}</td>
                                        <td>{{$Company->website}}</td>
                                        <td>
                                            <img class="img-thumbnail" style="max-width: 10rem" src="{{ url('storage/Company/'.$Company->logo)}}" alt="{{$Company->logo}}">
                                        </td>
                                        <td>{{$Company->addedByAdmin->name}}</td>
                                        <td>
                                            <a href="{{route('admin.company.edit', ['id' => $Company->id])}}" class="btn btn-info" title="Edit Company">Edit</a>
                                            <a href="{{ route('admin.company.delete', ['id' => $Company->id]) }}" class="btn btn-danger" title="Edit Company">Delete</a>
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <td colspan="6" class="text-center text-danger">No Company Found</td>
                            @endif
                        </tbody>
                    </table>
                    <div class="float-right">{{ $Companies->links() }}</div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection